[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
rootstock_testnet = "https://public-node.testnet.rsk.co"

